### ISSUE TITLE
Asynchronous hooks

### ISSUE THREAD

**Issue by orinocai** [dadi/api#103]
Making hooks asynchronous would support more complex operations, e.g. looking up data from another collection, querying a 3rd party API, chaining further model creation.

The use case for this is avoiding using custom endpoints for model-specific pre/post-processing.

At present, if we want to lookup data before inserting a document we must add that logic in a custom endpoint. But doing so hides that logic from other endpoints and leaves open other routes (the default collection endpoint and `model.create`) that don't share the same logic.

Asynchronous hooks would help us to keep model-specific logic where it belongs.

**Comment by eduardoboucas** [comment]
Just to add a bit more context, @orinocai mentioned to me that he needed to run more complex operations within a hook file (such as querying a collection), which reminded me that @mingard mentioned a similar requirement not too long ago.

The only issue with doing this as it stands is that hooks are synchronous, so any asynchronous operation that runs on a `beforeCreate`/`beforeUpdate`/`beforeDelete` hook will fire, but the API operation will not wait for its completion.

The solution for this is to add support for asynchronous hooks, which will cause the API operation to wait for all hooks to finish running. Because simply changing the existing logic to treat hooks as asynchronous operations would mean a breaking change for existing hooks, I propose a `async` property within the hook definition — when true, the hook will be handled with a Promise.

There's probably no point in implementing this on `after` hooks, because there's is nothing to wait for.

Any thoughts @jimlambie @mingard?

**Comment by josephdenne** [comment]
Can we get a specific use case or two for this please @eduardoboucas?

**Comment by eduardoboucas** [comment]
@josephdenne Currently, hooks are being used for simple synchronous operations, such as automatically populating a `slug` field from a `title` when a document is created or updated, for example.

Asynchronous hooks would allow for more complex operations to take place, such as querying or updating other documents. For example, you could intercept a document that is about to be inserted and create any tags or categories required, take the newly created IDs and append them to the document — I believe this is very similar to the requirement @mingard had a few weeks ago.

Another example could be to interact with a third-party service. You could insert a document with a YouTube URL and create a hook that pings the YouTube API and grabs information to populate the `title` and `author` fields.

I'm not suggesting we just move all business logic to hooks, but it seems to me that allowing hooks to be asynchronous would complement the existing implementation without any trade-offs.

**Comment by orinocai** [comment]
@josephdenne @eduardoboucas I have a specific use case for a shop checkout… maybe Monocle in the future...

When creating an order I need to validate a given promo code and apply a discount to the total price.

I can only do this with an asynchronous ‘beforeCreate’ hook because I need to lookup the discount and modify the price before the document is inserted.

I could of course put this logic into a custom endpoint; this does seems to be the current idiom. However, it seems fragile because we can still create an order at the default collections endpoint and also directly from another endpoint using `Model(‘order’).create()`. In both these cases the promo code would not be applied.

It’s possible that hooks aren’t the right mechanism to achieve this. Not wanting to rock the boat too much, but is it worth examining why we have custom endpoints at all? In theory would could simply attach our business logic to the model and only use the collection endpoints - then there’d only be one route to our logic.
