### ISSUE TITLE
Compose option for hooks

### ISSUE THREAD

**Issue by mingard** [dadi/api#105]
Currently hooks are only able to utilise the un-resolved values of a new or existing document. 

A typical example of a new document as it would appear to a hook
```JSON
{
  "foo": "bar",
  "referencedDocuments": [
    "576ba3602f5a57d1456c351f",
    "576ba3642f5a57d1456c365d"
  ]
}
```

Whilst it would not be possible to resolve the entire document because it doesn't exist, it would be possible to resolve the input Object by using the collection schema to resolve Reference fields, as compose does when retrieving a document.

```JSON
{
  "foo": "bar",
  "referencedDocuments": [
     {
      "_id": "576ba3602f5a57d1456c351f",
      "name": "yours"
    },
    {
      "_id": "576ba3642f5a57d1456c365d",
      "name": "westfm"
    }
  ]
}
```

Use case: A URL hook that requires values from Reference documents to build

**Comment by eduardoboucas** [comment]
I honestly think this shouldn't be included in the core hooks functionality. 

As they currently stand, hooks are very simple constructs and were made intentionally dumb. They simply take care of executing custom pieces logic at key points in the lifecycle of a request, delegating to the developer all the responsibility of what actually is executed and how.

For example, when a `beforeCreate` is fired, the only data we have access to at that point is the list of fields to be created. On a `beforeUpdate`, it's the update query (we don't even know what the document looks like at this point, or even if there is a document). These hooks are executed *before* any contact has been made with the database and I think it would be a mistake to change that.

Even though it may seem like a simple request, what you're asking is to change dramatically the philosophy of hooks. To do what you want, we first need to start inspecting and iterating through the documents, look into their schemas to find Reference fields, then run one or multiple queries to the database (how do handle errors on these?) and then finally run (or abort) the main request. This means that we can be doing multiple round trips to the database without making that clear to the developer.

The use case you're describing is perfectly possible since we've introduced asynchronous hooks in #104, as you can build a hook that manually grabs the IDs and uses the document model to run queries against them, generating the composed values you're after. By doing that in the hook itself, you'll be in full control of what happens and the core stays generic. And if you find that you require this behaviour multiple times, just make a generic hook for it — they were built as modular, self-contained files for that same reason.

In my opinion, hooks should be generic tools to allow developers to implement solutions they fully control, and if we try to make them "smart" we're introducing complexity and maintainability problems we don't need.

Just my two cents! 😇

**Comment by jimlambie** [comment]
That was at least twenty cents. Fully agree.

**Comment by mingard** [comment]
Good points, well made
