### ISSUE TITLE
Extended predicates / JOQULAR support

### ISSUE THREAD

**Issue by mingard** [dadi/api#175]
By introducing extended predicate methods to be used when querying it would be possible to filter content based on more than the default mongodb query methods. For example:

Currently there is a timeout based task referenced in #174 that requires the value of an object field value to be changed at a particular time to make it filterable and indexable.

The field:
```JSON
"publishedState": {
  "start": 1484567260,
  "end": 1484594112,
  "state": "scheduled"
}

```

And after scheduled changes:

```JSON
"publishedState": {
  "start": 1484567260,
  "end": 1484594112,
  "state": "published"
}

```

This can be filtered as follows:
```
?filter={”publishedState.state”: "published"}
```

But if we introduce the **$now** predicate we can filter like this:

```
?filter={”publishedState.start”: {”$gt": “$now”}}
```

The other requirement to fully satisfy the query would be the ability to query:
```
?filter={”publishedState.start”: {”$gte": “$now”, ”$lte": "publishedState.end"}}
```

**Comment by eduardoboucas** [comment]
Because we now have to support multiple database engines, we need to handle this type of operators on a per case basis. Support for `$now` [has been added](https://github.com/dadi/api/blob/develop/dadi/lib/model/utils.js#L143-L163), so I suggest we open individual tickets for new operators as and when we need them.
