### ISSUE TITLE
Filter returned fields by schema

### ISSUE THREAD

**Issue by mingard** [dadi/api#296]
If data is inserted directly into mongo, api will return it regardless of the collection schema. Passing the fields back to API causes missing field errors, so I believe it makes sense to remove them from payload.

**Comment by jimlambie** [comment]
I'm not sure of the best way to handle this. It _could_ be slightly confusing if you've entered data into the database but aren't getting it back when requesting documents from API. Should we remove it from the payload but also return a message or error block explaining what's what?

**Comment by jimlambie** [comment]
@mingard @fra967 @eduardoboucas @feroviktor 

We'd love some input from you all on this one!

**Comment by fra967** [comment]
I think it's the expected behaviour (to return all fields - even those not in the schema) and it has worked quite well so far, otherwise we would have had all sort of issues (think how timestamps and internal fields changed over time).
I look at the schema as a validation / filtering tool for writing data, not for reading it.

Additional fields could be present in the data because

- schema changed over time; yes this could be approached by using schema versioning, but it is far more pragmatic to just return all of them
- the database could be used by other APIs, (or have been used in the past, ad example for migrated data)

If you want to make it strict (i.e. return only fields in the schema) it's ok but please make it configurable and with its default setting to false (i.e. leaving it as it is now)

**Comment by mingard** [comment]
The `strict` flag sounds like the best solution.

**Comment by jimlambie** [comment]
@mingard, apologies didn't realise there'd been more comments here. What project is this currently a requirement for ?

**Comment by mingard** [comment]
@jimlambie No problem. I'll DM you about the project.

**Comment by jimlambie** [comment]
Closed, not required for any current API usage. Agree with comment by @fra967 above.
