### ISSUE TITLE
Publish can't create required collections with auth check created by @dadi/cli

### ISSUE THREAD

**Issue by danwdart** [dadi/api#429]
Mongo tokens collection was created with "type" as key of "admin" or "user" so shouldn't this be "type" as well?:
https://github.com/dadi/api/blob/0837a01d985a7171f2a87119fa38b045edeefb69/dadi/lib/auth/index.js#L75

Seems without this I can't hit a /config endpoint and have it work.

**Comment by jimlambie** [comment]
@danwdart wouldn't it be easier to modify the property in the Mongo collection?

**Comment by danwdart** [comment]
Whichever would be the most sensible to do. This is just how it came by default.

**Comment by danwdart** [comment]
CLI did this, I believe, unless API itself comes with defaults: https://github.com/dadi/cli/blob/ab8ea80a9ed7baee5e9fc6e2385f31e49cdfbe66/core/entryPoints/api/commands/clients-add/create-records-api-v3.js

**Comment by eduardoboucas** [comment]
Interesting. Worth noting that this will change drastically in API with the introduction of #396. I think we'll use `type: 'admin'` to determine whether a user has root/admin access, so `accessType` will no longer be used.

As a temporary measure, I would suggest modifying the Mongo record to include `accessType` just so that API doesn't complain. If this becomes a more pressing issue, we could release a patch for 3.x that looks for `type` instead of `accessType`.

**Comment by danwdart** [comment]
That's what I suggest yes, at the moment the latest version of cli is just not compatible with the latest publish and breaks the instructions provided in the docs. I can edit this one case on a case by case but still likely to affect new installations by other users.

**Comment by eduardoboucas** [comment]
Actually, `accessType` seems to be used consistently in API, so we should probably stick with that and update CLI instead, making it use `accessType` instead of `type`.

What say you, @jimlambie?

**Comment by eduardoboucas** [comment]
CLI has been updated to use `accessToken`, so this can be closed.

**Comment by danwdart** [comment]
Nice - thank you
