### ISSUE TITLE
Remove /config endpoints for creating/update collections, endpoints and hooks

### ISSUE THREAD

**Issue by jimlambie** [dadi/api#442]

**Comment by danwdart** [comment]
I would have added "make it commit itself in git and PR" but I'm probably too used to github pages and dynamic endpoints doing that.
Realistically if there were DB based endpoints and schemata this would probably be a lot easier to keep...

**Comment by danwdart** [comment]
Bear in mind, the Publish "add the users collection and hooks" uses this, so docs will need to be updated reflecting the manual way of doing this now (via a copy or some other thing).

**Comment by eduardoboucas** [comment]
> I would have added "make it commit itself in git and PR" but I'm probably too used to github pages and dynamic endpoints doing that.

That'd be nice, but to me that sounds more like something a third-party app or build system could do, since we're simply talking about listening to a request, pushing something to a repository and possibly triggering a build. I don't think that belongs in API.

> Bear in mind, the Publish "add the users collection and hooks" uses this, so docs will need to be updated reflecting the manual way of doing this now (via a copy or some other thing).

Very true. That functionality will be removed once Publish starts working with ACL, so the two things will happen in tandem – once we change Publish to work with ACL in API 4.0, it stops relying on the `/config` endpoints.

**Comment by danwdart** [comment]
Sounds good to me.
