### ISSUE TITLE
Cache pre warming

### ISSUE THREAD

**Issue by josephdenne** [dadi/api#50]
In large scale product implementations where a lot of collections and endpoints are in play, unpredictable traffic patterns can - and frequently do - lead to significant database load. This neccessatates high capacity infrastructure above and beyond normal operating thresholds.

The ability to pre warm API's cache _could_ mitigate against this and reduce infrastructure costs.

The concept is that a API understands the breadth of collections and endpoints that it contains, and then iteratively caches the common requests responses, preventing load spikes as a result of unpredictable user activity. In the event that a cached object expires, API would repopulate the cache automatically.

Pre warming would need to be sequential in order to prevent it from triggering load issues itself. It would also need to be configurable.

Thoughts on this request appreciated.

**Comment by jimlambie** [comment]
@josephdenne where would you configure this? In a collection schema or in the main config?

Perhaps a setting for "autoCache" against a collection? Although keeping it central in main config might help with maintenance. 

Specifying it like below would make it easy to determine if cache warming was enabled when it comes time to check expiry.

```
cache: {
  directory: {}
  redis: {}
  autoCache: {
    collections: [
      "/1.0/reviews/editions"
    ]
  }
}
```

### Key/Collection Endpoint Pattern

Cache keys are differentiated by the full request URL, so we can cache

### Timing

Redis expires keys automatically, so we'd need to do it on a TTL+x basis, where we sort of assume that a key has expired and fire a request for it again.

**Comment by jimlambie** [comment]
After some investigation into this issue we have decided not to pursue it.

We don't feel that API actually would ever actually need to make a decision to re-fetch data 
on it's own. For every request, API checks the cache to see if the data is available, and if 
not it generates it, caches it, and returns it. This occurs on the first request for data
and the first request after the cached data has expired after it's TTL is reached.

If the API is under load, only the first request will be an issue because after that 
the response is cached. So pre-warming will only make a difference for that first request, and 
adding pre-warming is a lot of work to save a ~500ms call.

Perhaps some ways to address this would be to: 

1) stagger TTL for various collections (and in fact, a bigger issue
here is that a collection's `cacheTTL` property is never used...)

2) write smoke tests for use when deploying the software so that often-requested data
is cached as part of the deployment, providing cached data before the regular traffic
begins requesting data

@eduardoboucas @josephdenne > thoughts appreciated
