### ISSUE TITLE
Hooks: endpoint

### ISSUE THREAD

**Issue by mingard** [dadi/api#78]
There is a requirement for 3 endpoints to aid in the delivery of hook config and availability.

- [ ]  `/hooks` to deliver a list of all available hooks, including a message/label, required and optional parameters, and available methods e.g. `beforeCreate` or `beforeDelete`
- [ ] `/hooks/{hookSlug}` used to deliver field values to aid with real-time output preview
- [ ] `/hooks/{hookSlug}/config` returns the full JS file used in the hook - TBD in Publish

**Comment by eduardoboucas** [comment]
It's worth noting that hooks currently exist in the form of individual JS files in `workspace/hooks`, and the only metadata they hold is their slug (which defined by the filename). 

If we want this endpoint to deliver more metadata about them, like a label and a list of parameters, this will have to be stored either in annotated comments in the hook file and parsed by the documentation middleware, or we need to introduce a JSON config file to accompany each hook. Depending on its feasibility, I would prefer the former, to avoid introducing another file.

^ @jimlambie would be great to have your thoughts on that.

Regarding the listing of available methods (`beforeCreate`, `beforeDelete`, etc.), it's important to mention that hooks are supposed to implement a piece of logic that is independent of the moment it's triggered at — as an example, if you think of a very simple hook that sends a message to a Slack channel, it's completely up to the engineer to decide when that should fire, as the hook will work every time.

Because in theory any hook can fire at any of the current 6 available "moments" (`beforeCreate`, `afterCreate`, `beforeUpdate`, `afterUpdate`, `beforeDelete` and `afterDelete`), can't we hardcode those options in Publish and update accordingly if API introduces more in the future? Or do you think it's still worth setting listing these in the endpoint?

**Comment by mingard** [comment]
@eduardoboucas if they're all capable of running at any point in the db write process thats fine - I was wondering if that was the case. I can say some potential for hooks that can only run in certain parts of the process, but for now, let us not over complicate it.

A basic descriptive message sounds fine - no need to over engineer there either. 

In short: your plan sounds perfect.
